function[careDistTable] =  continuumOfCareTargetPlots(sim_names,directories,year1,year2,savePath)

%this script evaluates the CoC distribution and determines if it is
%consistent with surveillance. It outputs data in a table as well as making
%a cool plot. note that
%you change the plotting parameters inside this file, which are at the
%beginning right after these comments.

% The inputs are

%   sim_names: name of the simulation you want to analyze. Usually follows
%   some sort of name like "outcome_AV_11_28_10xInCareAware". No need to
%   add the .mat. Because of how matlab reads cells, you will need to make
%   sure to input as:
%   continuumOfCareTargetPlots({'outcome_AV_11_28_10xInCareAware'},... 
%   with the curly braces.
%
%   directories: this is the directory where your simulation .mat data file
%   is found. For our purposes this is basically always going to be
%   '.\outcomes\". As with sim_names, you need the curly braces in the input, IE:
%      continuumOfCareTargetPlots({'outcome_AV_11_28_10xInCareAware'},{'.\outcomes\},...
%      
%   year1, year2: self-explanatory. years you want to look at
%
%  savePath: saves the resulting table in a place for your data. This done with
%  ".\HopeStudy\NAME_OF_SIMULATION\". Do NOT use curly brace rule here.
%
% so you might call , putting it all together
%
%   careDistTable =
%   continuumOfCareTargetPlots({'outcome_AV_11_28_10xInCareAware'},{'.\outcomes\},
%   2017, 2019, '.\HopeStudy\AV_11_28_10xInCareAware\');
%
% Plotting parameters are at very top of code for easy changing.

% It returns a bunch of mortality related outputs.


%target for pct aware (2019 surveillance)
pctAwareTarget=0.866766;
%target for pct in care (2019 surveillance)
pctInCareTarget=0.759962;
%target for pct VLS (2019 surveillance)
pctVLSTarget=.655;

fs=12; % font size
legendfs=10; %legend font size
lw=3; %line width
ms=12; %marker size
posMat=[-1750 -200 1750 400]; %plot size+position

%pretty colors
colorMat=[0 .4470 .7410;...
         .85 .325 .098;...
         .929 .694 .125;...
         .494 .184 .556;
         .466 .674 .188;
         .3010 .7450 .9330;
         .6350 .0780 .1840;
         .274 .119 .84;
         .725 .525  .38;
         .112 .917 .640];

     

load(strcat(directories{1},sim_names{1},".mat"));        
years=eval(sim_names{1}).set_ModelStartYear:1:eval(sim_names{1}).set_ModelEndYear;
years=years';

year_inds=find(years>=year1 & years<=year2);


%General pop. deaths?
numTotalDeaths=[0;(eval(sim_names{1}).ann_CumulativeNumNormDeath)*ones(273,1)];
numTotalDeaths=round(diff(numTotalDeaths));

%Deaths
numDeathsUndiag=round(eval(sim_names{1}).ann_numDeathsHIVPosUndiag*ones(273,1));
numDeathsCCStage2=round(eval(sim_names{1}).ann_numDeathsCCStage2*ones(273,1));
numDeathsCCStage3=round(eval(sim_names{1}).ann_numDeathsCCStage3*ones(273,1));
numDeathsCCStage4=round(eval(sim_names{1}).ann_numDeathsCCStage4*ones(273,1));
numDeathsVLS=round(eval(sim_names{1}).ann_numDeathsVLS*ones(273,1));

careContinuumDeaths=[numDeathsUndiag numDeathsCCStage2 numDeathsCCStage3 numDeathsCCStage4 numDeathsVLS];

numAIDSDeathsUndiag=round(eval(sim_names{1}).ann_numAIDSDeathsHIVPosUndiag*ones(273,1));
numAIDSDeathsCCStage2=round(eval(sim_names{1}).ann_numAIDSDeathsCCStage2*ones(273,1));
numAIDSDeathsCCStage3=round(eval(sim_names{1}).ann_numAIDSDeathsCCStage3*ones(273,1));
numAIDSDeathsCCStage4=round(eval(sim_names{1}).ann_numAIDSDeathsCCStage4*ones(273,1));
numAIDSDeathsVLS=round(eval(sim_names{1}).ann_numAIDSDeathsVLS*ones(273,1));

careContinuumAIDSDeaths=[numAIDSDeathsUndiag numAIDSDeathsCCStage2 numAIDSDeathsCCStage3 numAIDSDeathsCCStage4 numAIDSDeathsVLS];

%Prevalence

numUndiag=round(eval(sim_names{1}).ann_NumberUnaware*ones(273,1));
numCCStage2=round(eval(sim_names{1}).ann_NumberCCStage2*ones(273,1));
numCCStage3=round(eval(sim_names{1}).ann_NumberCCStage3*ones(273,1));
numCCStage4=round(eval(sim_names{1}).ann_NumberCCStage4*ones(273,1));
numVLS=round(eval(sim_names{1}).ann_NumberCCStages45*ones(273,1));
numVLS=numVLS-numCCStage4;

numAIDSUndiag=round(eval(sim_names{1}).ann_NumberAIDSUndiag*ones(273,1));
numAIDSCCStage2=round(eval(sim_names{1}).ann_NumberAIDSCCStage2*ones(273,1));
numAIDSCCStage3=round(eval(sim_names{1}).ann_NumberAIDSCCStage3*ones(273,1));
numAIDSCCStage4=round(eval(sim_names{1}).ann_NumberAIDSCCStage4*ones(273,1));
numAIDSVLS=round(eval(sim_names{1}).ann_NumberAIDSVLS*ones(273,1));


careContinuum=[numUndiag numCCStage2 numCCStage3 numCCStage4 numVLS];


%All PWH?
numDeaths=careContinuumDeaths*ones(5,1);
numAIDSDeaths=careContinuumAIDSDeaths*ones(5,1);
annPrev=careContinuum*ones(5,1);

careContinuumPct=careContinuum./annPrev;



totalPop=round(eval(sim_names{1}).ann_PopulationSize*ones(273,1));   
aidsPrev=round(eval(sim_names{1}).ann_NumberAIDS*ones(273,1));
annPrevNoAIDS=annPrev-aidsPrev;

totalPop=totalPop-aidsPrev;
numNormDeaths=numDeaths-numAIDSDeaths;
numTotalDeaths=numTotalDeaths-numNormDeaths;

deathRateHIV=numDeaths./annPrev;
%deathRateAIDS=numAIDSDeaths./aidsPrev;
%deathRateNorm=numNormDeaths./(annPrevNoAIDS);
deathRateAIDS=numAIDSDeaths./annPrev;
deathRateNorm=numNormDeaths./(annPrev);

deathRateUndiag=numDeathsUndiag./numUndiag;
%deathRateAIDSUndiag=(numAIDSDeathsUndiag)./(numAIDSUndiag);
%deathRateNormUndiag=(numDeathsUndiag- numAIDSDeathsUndiag)./(numUndiag-numAIDSUndiag);
deathRateAIDSUndiag=(numAIDSDeathsUndiag)./(numUndiag);
deathRateNormUndiag=(numDeathsUndiag- numAIDSDeathsUndiag)./(numUndiag);


deathRateCCStage2=numDeathsCCStage2./numCCStage2;
%deathRateAIDSCCStage2=(numAIDSDeathsCCStage2)./(numAIDSCCStage2);
%deathRateNormCCStage2=(numDeathsCCStage2- numAIDSDeathsCCStage2)./(numCCStage2- numAIDSCCStage2);
deathRateAIDSCCStage2=(numAIDSDeathsCCStage2)./(numCCStage2);
deathRateNormCCStage2=(numDeathsCCStage2- numAIDSDeathsCCStage2)./(numCCStage2);

deathRateCCStage3=numDeathsCCStage3./numCCStage3;
%deathRateAIDSCCStage3=(numAIDSDeathsCCStage3)./(numAIDSCCStage3);
%deathRateNormCCStage3=(numDeathsCCStage3- numAIDSDeathsCCStage3)./(numCCStage3- numAIDSCCStage3);
deathRateAIDSCCStage3=(numAIDSDeathsCCStage3)./(numCCStage3);
deathRateNormCCStage3=(numDeathsCCStage3- numAIDSDeathsCCStage3)./(numCCStage3);

deathRateCCStage4=numDeathsCCStage4./numCCStage4;
%deathRateAIDSCCStage4=(numAIDSDeathsCCStage4)./(numAIDSCCStage4);
%deathRateNormCCStage4=(numDeathsCCStage4- numAIDSDeathsCCStage4)./(numCCStage4- numAIDSCCStage4);
deathRateAIDSCCStage4=(numAIDSDeathsCCStage4)./(numCCStage4);
deathRateNormCCStage4=(numDeathsCCStage4- numAIDSDeathsCCStage4)./(numCCStage4);

deathRateVLS=numDeathsVLS./numVLS;
%deathRateAIDSVLS=(numDeathsVLS)./(numAIDSVLS);
%deathRateNormVLS=(numDeathsVLS- numAIDSDeathsVLS)./(numVLS- numAIDSVLS);
deathRateAIDSVLS=(numAIDSDeathsVLS)./(numVLS);
deathRateNormVLS=(numDeathsVLS- numAIDSDeathsVLS)./(numVLS);


deathRateGeneralPop=numTotalDeaths./totalPop;

numDiag=annPrev-numUndiag;
numInCare=numDiag-numCCStage2;

pctPWHUndiag=numUndiag(year_inds)./annPrev(year_inds);
pctPWHCCStage2=numCCStage2(year_inds)./annPrev(year_inds);
pctPWHCCStage3=numCCStage3(year_inds)./annPrev(year_inds);
pctPWHCCStage4=numCCStage4(year_inds)./annPrev(year_inds);
pctPWHVLS=numVLS(year_inds)./annPrev(year_inds);
pctPWHInCare=numInCare(year_inds)./annPrev(year_inds);
pctPWHDiag=numDiag(year_inds)./annPrev(year_inds);

pctDiagCCStage2=numCCStage2(year_inds)./numDiag(year_inds);
pctDiagCCStage3=numCCStage3(year_inds)./numDiag(year_inds);
pctDiagCCStage4=numCCStage4(year_inds)./numDiag(year_inds);
pctDiagVLS=numVLS(year_inds)./numDiag(year_inds);
pctDiagInCare=numInCare(year_inds)./numDiag(year_inds);

rateTable=[years(year_inds)...
            annPrev(year_inds)...
            numUndiag(year_inds)...
            numCCStage2(year_inds)... 
            numCCStage3(year_inds)... 
            numCCStage4(year_inds)... 
            numVLS(year_inds)...
            pctPWHUndiag...
            pctPWHCCStage2...
            pctPWHCCStage3...
            pctPWHCCStage4...
            pctPWHVLS...
            pctPWHDiag...
            pctDiagCCStage2...
            pctDiagCCStage3...
            pctDiagCCStage4...
            pctDiagVLS...
            pctDiagInCare...
            ];

careDistTable=array2table(rateTable,'VariableNames',...
                       {'Year',...                    
                       'HIVPrevalence',...
                       'NumberUndiag',...  
                       'NumberCCStage2'...  
                       'NumberCCStage3',...  
                       'NumberCCStage4',...  
                       'NumberVLS',...  
                       'PctPWHUndiag',...  
                       'PctPWHCCStage2',...  
                       'PctPWHCCStage3',...  
                       'PctPWHCCStage4',...
                       'PctPWHVLS',...                       
                       'pctPWHDiag',...  
                       'pctDiagCCStage2',...  
                       'pctDiagCCStage3',...  
                       'pctDiagCCStage4',...  
                       'pctDiagVLS',...  
                       'pctDiagInCare',...  
                       });


subplot(1,3,1)
b=bar(years(year_inds),...
    [ annPrev(year_inds) numUndiag(year_inds) numCCStage2(year_inds) numCCStage3(year_inds) numCCStage4(year_inds) numVLS(year_inds) numInCare(year_inds) numDiag(year_inds) ]/1000 ...
    );
hold on
for i=1:8
    b(i).FaceColor=colorMat(i,:);
end
xlabel('Year','FontSize',fs,'Interpreter','latex');
ylabel('Annual Prevalence [thousands]','FontSize',fs,'Interpreter','latex');

legend(...
         { 'All PWH',...
           'Undiag',...
           'CCStage2',...
           'CCStage3',...
           'CCStage4',...
           'VLS',...
           'InCare',...
           'Diag'},...
     'FontSize',legendfs,...
     'Interpreter','latex',...
    'NumColumns',2 ...
   );
  
ax=ancestor(gca,'Axes');
ax.YAxis.Exponent=0;
set(gca,'FontSize',fs);

subplot(1,3,2)
newbar=bar(years(year_inds),...
      [ numUndiag(year_inds)./annPrev(year_inds) numCCStage2(year_inds)./annPrev(year_inds) numCCStage3(year_inds)./annPrev(year_inds) numCCStage4(year_inds)./annPrev(year_inds) numVLS(year_inds)./annPrev(year_inds) numInCare(year_inds)./annPrev(year_inds) numDiag(year_inds)./annPrev(year_inds) ] ...
    );
hold on
for i=1:7
    newbar(i).FaceColor=colorMat(i+1,:);
end
plot(years(year_inds),(years(year_inds)./years(year_inds))*pctAwareTarget,'--','Color','k','LineWidth',lw);  

xlabel('Year','FontSize',fs,'Interpreter','latex');
ylabel('\% of all PWH','FontSize',fs,'Interpreter','latex');

legend(...
         { 'Undiag',...
           'CCStage2',...
           'CCStage3',...
           'CCStage4',...
           'VLS',...
           'InCare',...
           'Diag',...
           '\% Diag target'},...
     'FontSize',legendfs,...
     'Interpreter','latex',...
    'NumColumns',2 ...
   );
ax=ancestor(gca,'Axes');
ax.YAxis.Exponent=0;
ylim([0 1]);
ax.XTick=years(year_inds);
set(gca,'FontSize',fs);

subplot(1,3,3)

b=bar(years(year_inds),...
    [  numCCStage3(year_inds)./numDiag(year_inds) numCCStage4(year_inds)./numDiag(year_inds) numVLS(year_inds)./numDiag(year_inds)  numInCare(year_inds)./numDiag(year_inds)  ] ...
    );
hold on
for i=1:4
    b(i).FaceColor=colorMat(i+3,:);
end
plot(years(year_inds),(years(year_inds)./years(year_inds))*pctInCareTarget,'--','Color','k','LineWidth',lw);  
plot(years(year_inds),(years(year_inds)./years(year_inds))*pctVLSTarget,'--','Color','b','LineWidth',lw);  
xlabel('Year','FontSize',fs,'Interpreter','latex');
ylabel('\% of Diag PWH','FontSize',fs,'Interpreter','latex');

legend(...
         {'CCStage3',...
           'CCStage4',...
           'VLS',...
           'InCare'...
           '\% InCare target',...
           '\% VLS target'...
           },...
     'FontSize',legendfs,...
     'Interpreter','latex',...
    'NumColumns',2 ...
   );
  
ax=ancestor(gca,'Axes');
ax.YAxis.Exponent=0;
set(gca,'FontSize',fs);
ax.XTick=years(year_inds);

set(gcf,'Position',posMat);


if(nargin>=5)
    save(strcat(savePath,'careDistTable'),'careDistTable');
end

% 
% subplot(2,2,4)
% 
% plot(...
%     years(year_inds),careContinuumPct(year_inds,1),...
%     '--s',...
%     'LineWidth',lw,...
%     'MarkerSize',ms,...
%     'Color',colorMat(3,:)...
%     );
% hold on
% plot(...
%     years(year_inds),careContinuumPct(year_inds,2),...
%     '--*',...
%     'LineWidth',lw,...
%     'MarkerSize',ms,...
%     'Color',colorMat(4,:)...
%     );
% plot(...
%     years(year_inds),careContinuumPct(year_inds,3),...
%     '--v',...
%     'LineWidth',lw,...
%     'MarkerSize',ms,...
%     'Color',colorMat(5,:)...
%     );
% plot(...
%     years(year_inds),careContinuumPct(year_inds,4),...
%     '--+',...
%     'LineWidth',lw,...
%     'MarkerSize',ms,...
%     'Color',colorMat(6,:)...
%     );
% plot(...
%     years(year_inds),careContinuumPct(year_inds,5),...
%     '--x',...
%     'LineWidth',lw,...
%     'MarkerSize',ms,...
%     'Color',colorMat(7,:)...
%     );
% xlabel('Year','FontSize',fs,'Interpreter','latex');
% ylabel('\% in care continuum stage ','FontSize',fs,'Interpreter','latex');
% 
% legend(...
%          {
%            'Undiag',...
%            'CCStage2',...
%            'CCStage3',...
%            'CCStage4',...
%            'VLS'},...
%      'FontSize',fs,...
%      'Interpreter','latex'...
%      );
%   
% ax=ancestor(gca,'Axes');
% ax.YAxis.Exponent=0;
% set(gca,'FontSize',fs);